MYSITE/MYSITE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('Users/', include('Users.urls')),
    path('MyApp/', include('MyApp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MYSITE/MyApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'MyApp'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name= 'index'),
    path('<int:pk>/', views.FoodDetail.as_view(), name='detail'),
    path('add/', views.ItemCreateView.as_view(), name='create_item'),
    path('update/<int:pk>/', views.ItemUpdateView.as_view(), name='update_item'),
    path('delete/<int:pk>/', views.ItemDeleteView.as_view(), name='delete_item'),
]

MYSITE/Users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='Users/login.html'), name='login'),
    path('logout/', views.logout_views, name='logout'),
    path('profile/',views.profile, name='profile'),
]

MYSITE/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

MYSITE/MyApp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name + ":" + str(self.item_price)
    
    def get_absolute_url(self):
        return reverse('MyApp:index')

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.DecimalField(max_digits=6, decimal_places=2)
    item_image = models.URLField(max_length=600, default='https://grandseasonscoquitlam.com/img/placeholders/comfort_food_placeholder.png')
    is_avaible = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Category(models.Model):
    name = models.CharField(max_length=100)
    added_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

MYSITE/Users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg', upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

MYSITE/MyApp/forms.py
from django import forms
from .models import Item 

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

MYSITE/Users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User 

class ResgisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

MYSITE/MyApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

# @login_required
# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list':item_list
#     }
#     return render(request,"MyApp/index.html", context)

class IndexClassView(ListView):
    model = Item
    template_name = "MyApp/index.html"
    context_object_name = 'item_list'

# def detail(request, id):
#     item = Item.objects.get(id=id)
#     context ={
#         'item':item
#     }
#     return render(request, 'MyApp/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = "MyApp/detail.html"
    context_object_name = 'item'

# def create_item(request):
#     form = ItemForm(request.POST or None)
#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             return redirect('MyApp:index') 

#     context = {
#         'form': form
#     }
#     return render(request, 'MyApp/item-form.html', context)

class ItemCreateView(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


# def update_item(request, id):
#     item = Item.objects.get(id=id)
#     form = ItemForm(request.POST or None, instance=item)
#     if form.is_valid():
#         form.save()
#         return redirect('MyApp:index')
#     context = {
#         'form': form
#     }
#     return render(request, 'MyApp/item-form.html', context)

class ItemUpdateView(UpdateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name_suffix = '_update_form'

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

# def delete_item(request, id):
#     item = Item.objects.get(id=id)
#     if request.method == 'POST':
#         item.delete()
#         return redirect('MyApp:index')
#     return render(request, 'MyApp/item-delete.html')

class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('MyApp:index')

MYSITE/Users/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, authenticate
from django.contrib import messages
from .forms import ResgisterForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = ResgisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    form = ResgisterForm()
    return render(request, 'Users/register.html', {'form': form})

def logout_views(request):
    logout(request)
    return render(request, 'Users/logout.html')

@login_required
def profile(request):
    return render(request, 'Users/profile.html')

MYSITE/MyApp/templates/MyApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body>

    <nav class="bg-blue-600 text-white">
        <div class="flex justify-between px-2 py-4">
            <a href="#" class="font-bold text-2xl">Food App</a>
            <div class="space-x-6">

                <a href="{% url 'profile' %}"> Welcome, {{ user.username }} !</a>

            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
            {% endif %}
            
            </div>
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div class="bg-green-500 text-white">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block body %}
    
    {% endblock %}
    
</body>
</html>

MYSITE/MyApp/templates/MyApp/detail.html
{% extends "MyApp/base.html" %}

{% block body %}
    <div class="m-10 flex">
        <div>
            <img class="w-128 rounded-lg" src="{{item.item_image}}" alt="">
        </div>
        <div class="mx-16 space-y-5">
            <div class="font-bold text-4xl">{{item.item_name}}</div>
            <div class="text-green-700 font-bold text-2xl">${{item.item_price}}</div>
            <div>{{item.item_desc}}</div>
            <div>
                {% if item.user == request.user %}
                <a class="bg-yellow-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'MyApp:update_item' item.id %}">Edit</a>
                <a class="bg-red-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'MyApp:delete_item' item.id %}">Delete</a>
                {% endif %}
            </div>

        </div>
    </div>    
{% endblock %} 


<!-- 
<h1> {{item.item_name}} </h1>
<h2> {{ item.item_desc}} </h2>
<h3> {{ item.item_price}} </h3> -->

MYSITE/MyApp/templates/MyApp/index.html
{% extends 'MyApp/base.html' %}

{% block body %}
    <div>
        {% for item in item_list %}
            <div class="m-10 flex w-1/2 mx-auto">
                <div>
                    <img class="w-64 rounded-lg" src="{{item.item_image}}" alt="">
                </div>
                <div class="mx-16">
                    <div class="font-bold">{{item.item_name}}</div>
                    <div>{{item.user.username}}</div>
                    <div>{{item.item_desc}}</div>
                    <div class="text-green-700 font-bold">${{item.item_price}}</div>
                </div>
                <div>
                    <a class="bg-red-500 text-white font-bold px-4 py-2 rounded-md" href="{% url 'MyApp:detail' item.id %}">View Details</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

MYSITE/MyApp/templates/MyApp/item-delete.html
<form method="post">
  {% csrf_token %}
  <h2>Are you sure you want to delete this item?</h2>
  <button type="submit">Confirm</button>
</form>

MYSITE/MyApp/templates/MyApp/item-form.html
{% extends 'MyApp/base.html' %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form }}

        <button type="submit">Save</button>
    </form>
{% endblock %}

MYSITE/MyApp/templates/MyApp/item_confirm_delete.html
<form method= "POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <button type="submit">Delete Item</button>
</form>

MYSITE/MyApp/templates/MyApp/item_form.html
{% extends 'MyApp/base.html' %}

{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1 class="mb-6 text-2xl font-bold">Add item</h1>
    <form method="POST" class="shadow-lg p-10 space-y-6 w-96">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div>
            {% for error in form.non_field_errors %}
                <div class="text-red-500">{{ error }}</div>
            {% endfor %}
        {% endif %}
        {% for field in form %}
            <div>
                <label for="">{{ field.label }}</label>
                <div class="border rounded p-2">{{ field }}</div>
            </div>
        {% endfor %}
        <button type="submit" class="bg-blue-500 text-white px-2 py-2 w-full">Add Item</button>
    </form> 
</div>

{% endblock %}

MYSITE/MyApp/templates/MyApp/item_update_form.html
<form method= "POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Item</button>
</form>

MYSITE/Users/templates/Users/login.html
{% extends 'MyApp/base.html' %}

{% block body %}
<div class= "flex flex-col items-center min-h-screen m-10">
    <h1>Login</h1>
    <form method="post" class= "shadow-lg p-10 space-y-10">
        {% csrf_token %}
        {% if form.non_field_errors %}
        <div>
            {% for error in form.non_field_errors %}
                <div class="text-red-500">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <div>
            <label for="">Username</label>
            <div class="border rounded p-2">{{ form.username }}</div>
        </div>
        <div>
            <label for="">Password</label>
            <div class="border rounded p-2">{{ form.password }}</div>
        </div>
        <button type="submit" class="bg-blue-500 text-white px-2 py-2 w-full">Login</button>
    </form>
</div>
{% endblock %}

MYSITE/Users/templates/Users/logout.html
<h2>You have been logged out.</h2>

MYSITE/Users/templates/Users/profile.html
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" >

MYSITE/Users/templates/Users/register.html
<form method="POST">
    {% csrf_token %}
    <h2>Register</h2>
    {{ form }}
    <button type="submit">Sign Up</button>
</form>